# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-26 04:58


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingerrors',
            name='data_uuid',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
