# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-21 14:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_auto_20190726_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawsubmissions',
            name='is_processed',
            field=models.SmallIntegerField(default=0),
        ),
    ]
