# Generated by Django 2.2.6 on 2020-01-01 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0003_auto_20191021_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendor.Model'),
        ),
        migrations.AlterField(
            model_name='formviews',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendor.ODKForm'),
        ),
        migrations.AlterField(
            model_name='odkform',
            name='form_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vendor.ODKFormGroup'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salutation',
            field=models.CharField(blank=True, default='Dear', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rawsubmissions',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendor.ODKForm'),
        ),
        migrations.AlterField(
            model_name='viewsdata',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendor.FormViews'),
        ),
        migrations.AlterField(
            model_name='viewtableslookup',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendor.FormViews'),
        ),
    ]
