# Generated by Django 2.2 on 2020-02-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0005_remove_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='parent_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
