# Generated by Django 2.2.6 on 2020-08-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0006_systemsettings_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='odkform',
            name='datetime_published',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='odkform',
            name='is_active',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='odkform',
            name='latest_upload',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='odkform',
            name='no_submissions',
            field=models.SmallIntegerField(default=0),
        ),
    ]
