# Generated by Django 4.1.1 on 2022-10-07 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0010_auto_20220309_0525"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingerrors",
            name="raw_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="vendor.rawsubmissions",
            ),
        ),
    ]
