# Generated by Django 4.1.1 on 2022-10-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0011_processingerrors_raw_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingerrors",
            name="data_uuid",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="processingerrors",
            name="err_comments",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="processingerrors",
            name="err_message",
            field=models.CharField(max_length=2000),
        ),
    ]
