# Generated by Django 4.1.1 on 2022-10-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0012_alter_processingerrors_data_uuid_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="processingerrors", unique_together={("err_code", "data_uuid")},
        ),
    ]
