# Generated by Django 4.1.1 on 2022-10-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0013_alter_processingerrors_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="processingerrors", unique_together=set(),),
    ]
