# Generated by Django 4.1.1 on 2022-11-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0014_alter_processingerrors_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawsubmissions",
            name="duration",
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
