# Generated by Django 3.2.1 on 2023-02-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0015_alter_rawsubmissions_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='odkformgroup',
            name='form_project',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='odkform',
            name='form_id',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
