# Generated by Django 3.2.1 on 2023-02-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0018_auto_20230214_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='odkformgroup',
            name='project_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
